name: lando-python-3
services:
  defaults:
    type: python
    command: python /app/http-server.py
  patch:
    type: python:3.10.1
  cli:
    type: python

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/python": ./../../