name: lando-python-2
services:
  defaults:
    type: python:2.7
  patch:
    type: python:2.7.14

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/python": ./../../